"""New DB fields in user model

Revision ID: 25e911362b67
Revises: 67add09ae7e8
Create Date: 2020-04-03 22:32:00.477954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e911362b67'
down_revision = '67add09ae7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'last_seen')
    op.drop_column('post', 'about_me')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.add_column('post', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    op.add_column('post', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
